server:
  port: 9090

mqtt:
  mode: 0
  server: tcp://192.168.1.6:1883
  internal-server: tcp://192.168.1.6:1884
  client-id: eventbus
  cleanSession: true
  connectionTimeout: 5
  keepAliveInterval: 20

