server:
  port: 9090

mqtt:
  mode: 0
  server: tcp://127.0.0.1:1883
  internal-server: tcp://127.0.0.1:1884
  client-id: eventbus
  cleanSession: true
  connectionTimeout: 5
  keepAliveInterval: 20

zigbee:
  host: 192.168.1.4
  port: 8001

device:
  zigbeeDevices:
    "0204": sensor1
    "1504": pm2.5

